
FIND_PATH(CBLAS_INCLUDE_DIR NAMES cblas.h HINTS ${CBLAS_INCLUDE_CUSTOM_PATHS} PATHS ${CBLAS_INCLUDE_SEARCH_PATHS})
# on Ubuntu 20.04, 
#   cblas.so has been merged into blas.so (libblas-dev or libopenblas-dev package) 
FIND_LIBRARY(CBLAS_LIBRARIES NAMES cblas blas HINTS ${CBLAS_LIB_CUSTOM_PATHS} PATHS ${CBLAS_LIB_SEARCH_PATHS})

FIND_LIBRARY(BLAS_LIBRARIES NAMES blas HINTS ${BLAS_LIB_CUSTOM_PATHS} PATHS ${BLAS_LIB_SEARCH_PATHS})

SET(LOOKED_FOR
  CBLAS_INCLUDE_DIR
  CBLAS_LIBRARIES
  BLAS_LIBRARIES
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(CBLAS DEFAULT_MSG ${LOOKED_FOR})

IF(CBLAS_FOUND)
  MESSAGE(STATUS "Found CBLAS & BLAS")
  MESSAGE(STATUS CBLAS_INCLUDE_DIR=${CBLAS_INCLUDE_DIR})
  MESSAGE(STATUS CBLAS_LIBRARIES=${CBLAS_LIBRARIES})
  MESSAGE(STATUS BLAS_LIBRARIES=${BLAS_LIBRARIES})
ENDIF(CBLAS_FOUND)
