
FIND_PATH(CBLAS_INCLUDE_DIR NAMES cblas.h HINTS ${CBLAS_INCLUDE_CUSTOM_PATHS} PATHS ${CBLAS_INCLUDE_SEARCH_PATHS})
FIND_LIBRARY(CBLAS_LIBRARIES NAMES cblas HINTS ${CBLAS_LIB_CUSTOM_PATHS} PATHS ${CBLAS_LIB_SEARCH_PATHS})

SET(LOOKED_FOR
  CBLAS_INCLUDE_DIR
  CBLAS_LIBRARIES
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(CBLAS DEFAULT_MSG ${LOOKED_FOR})

IF(CBLAS_FOUND)
  MESSAGE(STATUS "Found CBLAS")
  MESSAGE(STATUS CBLAS_INCLUDE_DIR=${CBLAS_INCLUDE_DIR})
  MESSAGE(STATUS CBLAS_LIBRARIES=${CBLAS_LIBRARIES})
ENDIF(CBLAS_FOUND)
