
FIND_PATH(LAPACKE_INCLUDE_DIR NAMES lapacke.h HINTS ${LAPACKE_INCLUDE_CUSTOM_PATHS} PATHS ${LAPACKE_INCLUDE_SEARCH_PATHS})
FIND_LIBRARY(LAPACKE_LIBRARIES NAMES lapacke HINTS ${LAPACKE_LIB_CUSTOM_PATHS} PATHS ${LAPACKE_LIB_SEARCH_PATHS})

SET(LOOKED_FOR
  LAPACKE_INCLUDE_DIR
  LAPACKE_LIBRARIES
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LAPACKE DEFAULT_MSG ${LOOKED_FOR})

IF(LAPACKE_FOUND)
  MESSAGE(STATUS "Found LAPACKE")
  MESSAGE(STATUS LAPACKE_INCLUDE_DIR=${LAPACKE_INCLUDE_DIR})
  MESSAGE(STATUS LAPACKE_LIBRARIES=${LAPACKE_LIBRARIES})
ENDIF(LAPACKE_FOUND)
