# $Id: ubuntu.cmake 1698 2013-03-01 12:26:30Z boman $

#FIND_PROGRAM(CMAKE_CXX_COMPILER NAMES icpc)
#FIND_PROGRAM(CMAKE_C_COMPILER   NAMES icc)

#SET(CMAKE_BUILD_TYPE "Debug" CACHE FILEPATH "" FORCE)

#SET(MKL_LIB_PATH      "$ENV{MKLROOT}/lib/intel64;$ENV{MKLROOT}/intel64" CACHE PATH "" FORCE)
#SET(MKL_INCLUDE_PATH  "$ENV{MKLROOT}/include"                           CACHE PATH "" FORCE)

#SET(TBB_LIB_PATH       "$ENV{TBBROOT}/lib/intel64" CACHE PATH "" FORCE)
#SET(TBB_DEBUG_LIB_PATH "$ENV{TBBROOT}/lib/intel64" CACHE PATH "" FORCE)
#SET(TBB_INCLUDE_PATH   "$ENV{TBBROOT}/include"     CACHE PATH "" FORCE)


SET(LAPACKE_LIB_PATH		"/usr/lib" CACHE PATH "" FORCE)
SET(LAPACKE_INCLUDE_PATH	"/usr/lib" CACHE PATH "" FORCE)
